/**
 * Extract frontend routes from App.tsx and generate a typed route manifest.
 *
 * Run: npx tsx scripts/extract-routes.ts
 * Output: fixtures/routes.generated.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const appTsxPath = resolve(__dirname, '../../frontend/src/App.tsx');
const outputPath = resolve(__dirname, '../fixtures/routes.generated.ts');

const IGNORED_ROUTES = [
  '/embed/vessel/:vesselId', // standalone page, no AppLayout
];

const source = readFileSync(appTsxPath, 'utf-8');

// Match <Route path="..." /> and <Route index ... />
const routeRegex = /<Route\s+(?:[^>]*?\s)?path=["']([^"']+)["'][^>]*>/g;
const indexRegex = /<Route\s+index\b/;

interface RouteEntry {
  path: string;
  name: string;
}

const staticPages: RouteEntry[] = [];
const paramPages: RouteEntry[] = [];

// Add index route if present
if (indexRegex.test(source)) {
  staticPages.push({ path: '/', name: 'Dashboard' });
}

let match: RegExpExecArray | null;
while ((match = routeRegex.exec(source)) !== null) {
  const routePath = '/' + match[1].replace(/^\//, '');

  if (IGNORED_ROUTES.includes(routePath)) continue;

  // Derive a name from the path
  const name = routePath
    .split('/')
    .filter(Boolean)
    .filter(s => !s.startsWith(':'))
    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
    .join('') || 'Root';

  if (routePath.includes(':')) {
    paramPages.push({ path: routePath, name });
  } else {
    staticPages.push({ path: routePath, name });
  }
}

const output = `// AUTO-GENERATED by scripts/extract-routes.ts — do not edit manually
// Extracted from frontend/src/App.tsx

export const STATIC_PAGES = ${JSON.stringify(staticPages, null, 2)} as const;

export const PARAM_PAGES = ${JSON.stringify(paramPages, null, 2)} as const;

export const ALL_ROUTES = [...STATIC_PAGES, ...PARAM_PAGES] as const;
`;

writeFileSync(outputPath, output, 'utf-8');

console.log(
  `Extracted ${staticPages.length} static + ${paramPages.length} parameterized routes → ${outputPath}`
);
