// AUTO-GENERATED by scripts/extract-routes.ts — do not edit manually
// Extracted from frontend/src/App.tsx

export const STATIC_PAGES = [
  { "path": "/", "name": "Dashboard" },
  { "path": "/alerts", "name": "Alerts" },
  { "path": "/vessels", "name": "Vessels" },
  { "path": "/map", "name": "Map" },
  { "path": "/sts-events", "name": "Sts-events" },
  { "path": "/corridors", "name": "Corridors" },
  { "path": "/watchlist", "name": "Watchlist" },
  { "path": "/fleet", "name": "Fleet" },
  { "path": "/ownership", "name": "Ownership" },
  { "path": "/ingest", "name": "Ingest" },
  { "path": "/detections", "name": "Detections" },
  { "path": "/dark-vessels", "name": "Dark-vessels" },
  { "path": "/merge-candidates", "name": "Merge-candidates" },
  { "path": "/hunt", "name": "Hunt" },
  { "path": "/detect", "name": "Detect" },
  { "path": "/accuracy", "name": "Accuracy" },
  { "path": "/data-health", "name": "Data-health" },
  { "path": "/admin/tips", "name": "AdminTips" },
  { "path": "/donate", "name": "Donate" }
] as const;

export const PARAM_PAGES = [
  { "path": "/alerts/:id", "name": "Alerts" },
  { "path": "/vessels/:id", "name": "Vessels" },
  { "path": "/vessels/:id/detectors", "name": "VesselsDetectors" },
  { "path": "/vessels/:id/voyage", "name": "VesselsVoyage" },
  { "path": "/vessels/:id/timeline", "name": "VesselsTimeline" },
  { "path": "/corridors/:id", "name": "Corridors" }
] as const;

export const ALL_ROUTES = [...STATIC_PAGES, ...PARAM_PAGES] as const;
